#!/bin/python
'''
	---------------------------Auto-Airodump-NG--------------------------- 
    Automates settings of Airodump allowing for quick and easy re-scanning.
    					Copyright (C) 2015 Jack Hall

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
      
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''
      
#Dependancies:
#Netifaces - use [pip install netifaces] to download

#Import modules
import os
import netifaces
import subprocess
import time

print("----------Automated Airodump-NG Script----------")

print("")

#Requests input for interfaces
w24 = input("Enter the network Interface: ")
moni = input("Enter The Monitor Interface(Default is mon0): ")

#Checks frequency entered
checker = 0
while checker == 0:
 ghz = input("2.4Ghz or 5Ghz Scanning? ")
 if ghz == "2.4" or ghz == "5":
  checker = checker + 1
 else:
  print("Incorrect Entry.  Enter only 2.4 or 5.")

print("")

#Initiates Airmon-NG
os.system("airmon-ng start %w24")

#Checks the interfaces, ensures they are active.
def interfaces():
 try:
  w24up = netifaces.ifaddresses(w24)
 except Exception:
  print("Interface: " + w24 + " Is Inactive")
  exit()
 try:
  moniup = netifaces.ifaddresses(moni)
 except Exception:
  print("Interface: " + moni + "Is Inactive")
 else:
  print("Interface: " + w24 + " Is Active")
  print("Interface: " + moni + " Is Active")

endit = 0

while endit == 0:
#Requests site for the user.  Site is location in building.
 site = str(input("What site are you scanning?"))
 if site == "q":
  endit =1

 interfaces()

 if ghz == "2.4":
  try:
   print("Performing 2 min scan.")
   os.setpgrp()
#Creates subprocess
   p = subprocess.Popen(["airodump-ng", moni, "-w", "./24_airodump_scan_site" + site])
#Sleeps for 2 mins
   time.sleep(2*60)
#Kills the airodump-NG process
   os.system("killall -15 airodump-ng")
  except Exception: 
   print("Error - 2.4Ghz")

 if ghz == "5":
  try:
    print("Performing 2 min scan.")
#Creates subprocess
    subprocess.Popen(["airodump-ng", moni, "--band", "a", "-w", "./5_airodump_scan_site" + site])
#Sleeps for 2 mins
    time.sleep(2*60)
#Kills airodump-NG process
    os.system("killall -15 airodump-ng")
  except Exception:
   print("Error - 5Ghz")
exit()
